EXTENSION_GSETTINGS_SCHEMAS_DIR := schemas

EXTENSION_GSETTINGS_SCHEMAS := \
    $(wildcard $(EXTENSION_GSETTINGS_SCHEMAS_DIR)/*.gschema.xml)

EXTENSION_GSETTINGS_SCHEMAS_COMPILED := \
    $(EXTENSION_GSETTINGS_SCHEMAS_DIR)/gschemas.compiled

$(EXTENSION_GSETTINGS_SCHEMAS_COMPILED): $(EXTENSION_GSETTINGS_SCHEMAS)
	glib-compile-schemas --strict $(dir $@)

schemas: $(EXTENSION_GSETTINGS_SCHEMAS_COMPILED)
schemas/clean:
	$(RM) $(EXTENSION_GSETTINGS_SCHEMAS_COMPILED)

all: schemas
clean: schemas/clean
.PHONY: schemas schemas/clean

EXTENSION_PACK_CONTENT += \
    $(EXTENSION_GSETTINGS_SCHEMAS) \
    $(EXTENSION_GSETTINGS_SCHEMAS_COMPILED)
