# Download VM image and verify sha256 checksum. Inputs:
# VM_NAME
# VM_IMAGE_URL
# VM_IMAGE_CHECKSUM_URL
# VM_DOWNLOAD_COMMAND

VM_DOWNLOAD_DIR := downloads/$(VM_NAME)

VM_IMAGE_FILE := $(VM_DOWNLOAD_DIR)/$(notdir $(VM_IMAGE_URL))
VM_IMAGE_CHECKSUM_FILE := $(VM_DOWNLOAD_DIR)/$(notdir $(VM_IMAGE_CHECKSUM_URL))
VM_IMAGE_CHECKSUM_GREP := $(VM_IMAGE_FILE).expected-sha256
VM_IMAGE_CHECKSUM_STAMP := $(VM_IMAGE_FILE).checksum-ok

VM_DOWNLOAD_FILES := \
	$(VM_IMAGE_FILE) \
	$(VM_IMAGE_CHECKSUM_FILE) \
	$(VM_IMAGE_CHECKSUM_GREP) \
	$(VM_IMAGE_CHECKSUM_STAMP)

$(VM_DOWNLOAD_DIR):
	mkdir -p $@

$(VM_DOWNLOAD_FILES): | $(VM_DOWNLOAD_DIR)

$(VM_IMAGE_FILE) $(VM_IMAGE_CHECKSUM_FILE):
	$(VM_DOWNLOAD_COMMAND)

$(VM_IMAGE_FILE): VM_DOWNLOAD_URL := $(VM_IMAGE_URL)
$(VM_IMAGE_CHECKSUM_FILE): VM_DOWNLOAD_URL := $(VM_IMAGE_CHECKSUM_URL)

$(VM_IMAGE_CHECKSUM_GREP): $(VM_IMAGE_CHECKSUM_FILE)
	grep -F $(VM_IMAGE_CHECKSUM_GREP_PATTERN) $< >$@

$(VM_IMAGE_CHECKSUM_GREP): VM_IMAGE_CHECKSUM_GREP_PATTERN := $(notdir $(VM_IMAGE_FILE))

$(VM_IMAGE_CHECKSUM_STAMP): $(VM_IMAGE_CHECKSUM_GREP) $(VM_IMAGE_FILE)
	cd $(dir $<) && sha256sum --strict -c $(notdir $<)
	touch $@

$(VM_NAME)/download: $(VM_IMAGE_CHECKSUM_STAMP)

$(VM_NAME)/distclean:
	$(RM) $(VM_DISTCLEAN)

$(VM_NAME)/distclean: VM_DISTCLEAN := $(VM_DOWNLOAD_FILES)

download: $(VM_NAME)/download
distclean: $(VM_NAME)/distclean
.PHONY: $(VM_NAME)/download $(VM_NAME)/distclean
